export const routes = {
  login: () => '/login',
  register: () => '/register',
  forgotPassword: () => '/forgot-password',
  resetPassword: () => '/reset-password',
  twoFactorChallenge: () => '/two-factor-challenge',
  emailVerified: () => '/api/email/resend',
  emailNotification: () => '/email/verification-notification',
  logout: () => '/logout',
  dashboard: () => '/',
  habits: () => '/api/habits',
  habit: id => `/api/habits/${id}`,
  habitComplete: id => `/api/habits/${id}/complete`,
  profile: () => '/profile',
  twoFactorSetup: () => '/profile/two-factor',
  user: () => '/api/user',
  errorTest: () => '/error-test',
};
